name: lirtcui
description: linux webrtc app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  websocket: ^0.0.5
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_webrtc: ^0.9.11
  web_socket_channel:
  sdp_transform:
  shared_preferences:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ca/
